"""o

Revision ID: 4414b00ed070
Revises: 7a1d3bfecb89
Create Date: 2020-06-02 22:29:34.048556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4414b00ed070'
down_revision = '7a1d3bfecb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('actor', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('country', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('picture', sa.String(length=300), nullable=True))
    op.add_column('post', sa.Column('time', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('year', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'year')
    op.drop_column('post', 'time')
    op.drop_column('post', 'picture')
    op.drop_column('post', 'country')
    op.drop_column('post', 'actor')
    # ### end Alembic commands ###
